apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mysql-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/instance: mysql-pod
    spec:
      containers:
        - name: mysql-pod
          image: mysql:8.0.21
          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: MYSQL_ROOT_PASSWORD

          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
