apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: mysql-pod
  ports:
    - name: db
      port: 3306
      targetPort: 3306
      protocol: TCP
